[package]
name = "anyrun"
version = "0.1.0"
authors = ["Pengfei Zhang <zpfalpc23@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
serde_derive = "1.0.80"
serde = "1.0.80"
serde_json = "1.0.32"